### ISSUE TITLE
Import from FMP to PostgreSQL

### ISSUE THREAD

**Issue by bmitchinson** [Haiti-Distributed-Healthcare-System/hdhs#17]
- [x] Create PostgreSQL schema that matches FMP data.
- [x] Create a script that imports FMP data into a fresh PostgreSQL database.
- [x] Define foreign key relations
- [x] Thoroughly document how this works

**Comment by abpwrs** [comment]
https://fmhelp.filemaker.com/help/17/fmp/en/index.html#page/FMP_Help/odbc-jdbc.html

**Comment by meghanmc** [comment]
@zainakh Can you update this issue Re: progress on defining foreign key relations and updating the milestone (Sprint 5 vs Sprint 6)

**Comment by bmitchinson** [comment]
We should consider using datagrip if that makes the foreign key relations easier to visualize

**Comment by zainakh** [comment]
When converting the FMP to Postgres, we haven't found a way to extract the information on what attributes are connected to others. Due to naming convention of attributes (some have "fk" in their name), we have one-way knowledge on which ones have a foreign key to another table, and by convention this should connect to the primary key in the other table, however we haven't been successful with creating this constraint yet. 
- [ ] Review all the foreign key relationships in FMP database
- [ ] Test methods of adding them manually to the Postgres database
- [ ] Adapt to a general method to add all foreign key relationships
- [ ] Document this and submit pull request
